### ISSUE TITLE
link to  code is broken  Deep Learning Through A Telescoping Lens

### ISSUE THREAD

**Issue by Sandy4321** [alanjeffares/not-double-descent#1]
link to  code is broken 

Code is provided at https://github.com/alanjeffares/telescoping-lens

from 
https://arxiv.org/pdf/2411.00247
Deep Learning Through A Telescoping Lens:
A Simple Model Provides Empirical Insights On
Grokking, Gradient Boosting & Beyond

**Comment by alanjeffares** [comment]
Hello, thanks for your interest in our work! 

We are currently tidying up the code which we intend to release before NeurIPS 2024. I have now made an (empty) repository at that link so this is clear.
